### ISSUE TITLE
ESLint導入

### ISSUE THREAD

**Issue by NXVZBGBFBEN** [NITKC-DEV/Kisarazu-Multi-Manager#138]
Prettier導入後にブランチを切って作業をする．
Prettierとは違いコード構造に対して大量の警告が出ると予想される．
コードが動かない訳ではないため設定ファイルのみ導入して，今後それぞれ修正していく方針でもアリ．

**Comment by starkoka** [comment]
担当割り振り

@NXVZBGBFBEN 
 -lintブランチ切り離し&導入
 
 @starkoka 
  - lint_kokastarブランチ切り離し
  - commandsフォルダ内dashboard.js、guildData.js、timeTable.js
  - functionフォルダ内CCFuncu.js以外
  
  @Kou-Ro 
    - lint_Kouroブランチ切り離し
   - フォルダに属さないファイル全部
   - commandsフォルダ内CreateChannel.js、General.js
   - functionフォルダ内CCFunc.js

**Comment by Kou-Ro** [comment]
未マージファイルである、
functions/functions.js
を自分の担当に追加
