### ISSUE TITLE
雨ふるよ警告

### ISSUE THREAD

**Issue by nairoki23** [NITKC-DEV/Kisarazu-Multi-Manager#236]
数分おきに天気をいい感じに取得できるAPIにaccessして、そろそろ雨がふりそうだなってなったら通知を送る。
新機能構想

**Comment by nairoki23** [comment]
ターゲットとしては洗濯物を干してる人とか散歩している人を想定している

**Comment by Kou-Ro** [comment]
どのAPI?
現状使ってる気象庁は一日に数回しか更新しないけど

**Comment by nairoki23** [comment]
APIという表現は悪かったかもしれません。
今のところ気象庁のアメダスを高頻度(1分間隔程度)でスクレイピングすることを検討しています。
他に代替手段を探して良いものがあればそちらを使うかもしれません。

**Comment by Kou-Ro** [comment]
気象庁のAPIはリアルタイム更新がない

**Comment by starkoka** [comment]
アメダスのデータって配信までに30分あるから気をつけてね

**Comment by nairoki23** [comment]
https://www.jma.go.jp/bosai/amedas/#area_type=offices&area_code=120000&amdno=45282&format=table10min&elems=53410
これを見た感じ10分間隔で更新してくれそうなんですけどどうですかね？

**Comment by starkoka** [comment]
> アメダス観測ネットワークから気象庁への情報配信にはタイムラグがあるため、最新データにはおよそ 30 分前のデータが記録されています。
っていう情報を見つけた。

**Comment by Kou-Ro** [comment]
たぶん、アメダスとか検知してから情報出す系だとあんま意味ないと思う。
予報じゃないと
まあ、周辺の降水状況から予測してもいいけど()

**Comment by nairoki23** [comment]
たしかに。
作りたいけどどうやって作るかは要検討ですね。

**Comment by starkoka** [comment]
めっちゃ正直な話すると、降ったり止んだりとか不安定な天気のときにただうるさくなるだけだと思う。それを同じ天気のチャンネルに送信させると、天気のチャンネルそのものをミュートされて結果として使わなくなるだけだと思われ

**Comment by starkoka** [comment]
第一、雨降ってるかどうかなんてカーテン開けて外見ればわかるからな

**Comment by Kou-Ro** [comment]
まじで中身読んでないけど共有
https://open-meteo.com/

**Comment by starkoka** [comment]
↑それ見たけどあんまり良くなさそうだったからやめた

**Comment by nairoki23** [comment]
確かにうるさくなる問題はありますね。
雨ふる直前の時間にリマインドをする仕様とかが現実的かな？

**Comment by Kou-Ro** [comment]
逆にもともとそういう実装にしようとしてたんじゃないの？

**Comment by starkoka** [comment]
これ実装する意味あるかな
わざわざDiscordで通知する必要ある勝ってところがあって、速報性でYahoo天気とウェザーニュースに絶対に勝てない以上、それ以外の観点でDiscordで通知するメリットを出さないといけないんだけど、ただうるさいだけになると思う

**Comment by starkoka** [comment]
23sサーバーでは既存の20時の天気通知のところ誰も話してなくてお通夜状態かもしれないけど、22sは一定数それによって会話が増えてて、そういう観点からすればYahho天気やウェザーニュースにはできないことを成し遂げられてると思うんだよね。

僕が心配なのは、この機能を実装することで、今ある既存の20時の天気通知までミュートされそうっていうところ。チャンネル分ければいいじゃんってなるかもしれないけど、最初からミュートされるであろうことがわかってる機能をわざわざ今からこのBOTに実装する意味はないと思う

**Comment by nairoki23** [comment]
確かに
アプリで別アプリで代替できそうですね。

**Comment by starkoka** [comment]
実際僕の中で天気機能を作ろう！ってなったときに考えたときに没にしたアイデアなので、他に画期的なアイデアがなければ没になると思います...(類似機能は同じ人が担当するため)

**Comment by nairoki23** [comment]
僕的には今回話してみてcloseで良いかなって感じです。
Discord botでしかできない機能を実装するべきということを私は改めて感じました。
